site_name: FreshBoy's Headspace
site_author: FreshBoy
site_description: FreshBoy's personal website, where you can find his notes, projects and blogs.

theme: 
  name: material
  palette:
    primary: amber
    scheme: slate
  features:
    - navigation.top
    - navigation.tabs
    - navigation.path
    - navigation.expand
    - navigation.indexes
    - navigation.instant

extra:
  social: # show GitHub, Twitter & Email at footage
    - icon: fontawesome/brands/github
      link: https://github.com/FreshBoy-cyh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FreshBoy_cyh
    - icon: fontawesome/solid/envelope
      link: mailto:yihangchen2003@gmail.com
  analytics:
    provider: google
    property: G-5D9MVMM08N

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - blog:
      post_url_format: "{file}"
  # - optimize

extra_javascript: # KaTeX
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - Homepage:
    - index.md
    - About Me: homepage/about_me.md
    - Friends: homepage/friends.md
  - EECS:
    - eecs/index.md
    - ZJU C Correction: eecs/clang/index.md
    - ZJU Discrete Math: https://github.com/FreshBoy-cyh/ZJU_Discrete_Mathematics_and_Its_Applications_Note
    - ZJU Computer Architecture:
      - eecs/arch/index.md
      - C1 Introduction: eecs/arch/1_intro.md
    - Music Processing Analysis:
      - eecs/mpa/index.md
      - 1 Representation: eecs/mpa/1_represent.md
      - 2 Fourier Transform & 3 Audio Features: eecs/mpa/2_3_feature.md
      - 4 Music Synchronization: eecs/mpa/4_sync.md
    - 'GCT634: Musical Applications of Machine Learning':
      - eecs/gct634/index.md
      - W1 Representation: eecs/mpa/1_represent.md
      - W2-4 Music Classification:
        - eecs/gct634/w2-4_classify/index.md
        - 'Ref: DeepMIR Lec3 Timbre': eecs/gct634/w2-4_classify/deepmir3.md
  - Linguistics:
    - ling/index.md
    - Middle Chinese Pronunciation:
      - ling/mid_ch/index.md
      - Onset: ling/mid_ch/onset.md
      - Tone & Coda: ling/mid_ch/tone_coda.md
      - Rime: ling/mid_ch/rime.md
    - Hawaiian Language:
      - ling/hawaii/index.md
      - 夏威夷文&发音: ling/hawaii/夏威夷文&发音.md
      - 夏威夷语语法: ling/hawaii/夏威夷语语法.md
  - Blog:
    - blog/index.md

