site_name: FreshBoy's Headspace
site_author: FreshBoy
site_description: FreshBoy's personal website, where you can find his notes, blogs and projects.

theme: 
  name: material
  palette:
    primary: amber
    scheme: slate
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes

extra:
  social: # show GitHub, Twi & E-mail at footage
    - icon: fontawesome/brands/github
      link: https://github.com/FreshBoy-cyh
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FreshBoy_cyh
    - icon: fontawesome/solid/envelope
      link: mailto:yihangchen2003@gmail.com
  analytics:
    provider: google
    property: G-XXXXXXXXXX

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript: # KaTeX
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - Homepage:
    - index.md
    - Friends: homepage/friends.md
  - EECS:
    - eecs/index.md
    - ZJU Discrete Math:
      - eecs/discrete/index.md
    - ZJU C Correction: eecs/C/index.md
    - 'GCT634: Musical Applications of Machine Learning':
      - eecs/GCT634/index.md
      - W1 Representations: eecs/GCT634/w1_represent.md
      - W2-4 Music Classification: eecs/GCT634/w2-4_classify.md
      - DeepMIT Lec3: eecs/GCT634/lec3.md
  - Linguistics:
    - ling/index.md
    - Middle Chinese Pronunciation:
      - ling/mid_ch/index.md
      - Onset: ling/mid_ch/onset.md
      - Tone & Coda: ling/mid_ch/tone.md
      - Rime: ling/mid_ch/rime.md
    - Hawaiian Language:
      - ling/hawaii/index.md
      - 夏威夷文&发音: ling/hawaii/夏威夷文&发音.md
      - 夏威夷语语法: ling/hawaii/夏威夷语语法.md
  - Blog:
    - blog/index.md
    - Failology in Math Modeling: blog/math_model.md
    - On Studying Abroad: blog/study_abroad.md
    - ZJU CS 大二上课程体验: blog/zjucs_2nd_autumn/index.md
    - UG in Half an Hour: blog/ug.md
